name: 'README the RSS'
description: 'Add your latest blog urls to your profile README'
inputs:
  feed_url:
    description: 'The URL of the RSS feed'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'